services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
