services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped

volumes:
  django_sqlite_data:
