name: Matrix workflow

on:
  workflow_dispatch:

jobs:
  matrix-workflow-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        python-version: [3.8, 3.9, 3.10]
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - name: NodeJs version
        run: |
          node -v
          python --version
          echo "NodeJs version: ${{ matrix.node-version }}"
          echo "Python version: ${{ matrix.python-version }}"
      
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NodeJs version after setup
        run: |
          node -v
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version after setup
        run: |
          python --version