name: Matrix workflow

on:
  workflow_dispatch:

jobs:
  matrix-workflow-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        python-version: [3.10]

    
    steps:
      - name: NodeJs version
        run: |
          echo "NodeJs version: ${{ matrix.node-version }}"

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NodeJs version after setup
        run: |
          node -v