name: Matrix workflow

on:
  workflow_dispatch:

jobs:
  matrix-workflow-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        python-version: [3.10]

    
    steps:
      - name: NodeJs version
        run: |
          echo "NodeJs version: ${{ matrix.node-version }}"

      - name: Python version
        run: |
          echo "Python version: ${{ matrix.python-version }}"