name: Value pass workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'unnamed'

jobs:
  get_value_pass_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Greetings Message
        id: get_greetings
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!" >> GITHUB_OUTPUT
          
  
  print_value_pass_job:
    runs-on: ubuntu-latest
    needs: get_value_pass_job
    steps:
      - name: Print value from previous job
        run: |
          echo "${{ needs.get_value_pass_job.outputs.get_greetings }}"