name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Django Docker image
        run: docker build -t myapp ./backend

      - name: Run tests in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/backend:/app \
            django-backend \
            python manage.py runserver